In [1]:
import pandas as pd
from wordcloud import WordCloud
import matplotlib.pyplot as plt

In [2]:
df=pd.read_csv('Data Science Jobs 2024.csv')
df.drop('Unnamed: 0',axis=1,inplace=True)
df.head()

,Job Title,Salary Estimate,Job Description,Rating,Company Name,Location,Size,Founded,Type of ownership,Industry,Sector,Revenue,URL
0,Data Analytics,$38.00 - $45.00 Per Hour (Employer est.),Minimum three years experience in data science...,3.9,J & S Consulting,"Tucker, GA",51 to 200 Employees,--,Company - Private,Information Technology Support Services,Information Technology,$5 to $25 million (USD),https://www.glassdoor.com/job-listing/data-ana...
1,Data Scientist,$120K - $130K (Employer est.),Data science: 1 year (Preferred). Expertise in...,4.0,element technologies,Remote,51 to 200 Employees,2000,Company - Private,Information Technology Support Services,Information Technology,Unknown / Non-Applicable,https://www.glassdoor.com/job-listing/data-sci...
2,Data Scientist,$66.82 - $80.54 Per Hour (Employer est.),End-to-end data and model pipeline deployment ...,4.4,Boston Technology,"Malvern, PA",51 to 200 Employees,2004,Company - Private,Information Technology Support Services,Information Technology,$5 to $25 million (USD),https://www.glassdoor.com/job-listing/data-sci...
3,Data Engineer,$105K - $160K (Employer est.),Communicates technical concepts to non-technic...,3.9,Costco Wholesale,"Dallas, TX",10000+ Employees,1976,Company - Public,General Merchandise & Superstores,Retail & Wholesale,Unknown / Non-Applicable,https://www.glassdoor.com/job-listing/data-eng...
4,Data Science Co-Op,$84K - $109K (Glassdoor est.),Work with source control tools like GIT to sav...,4.1,Hunter Engineering Company,"Bridgeton, MO",1001 to 5000 Employees,1946,Company - Private,Machinery Manufacturing,Manufacturing,$500 million to $1 billion (USD),https://www.glassdoor.com/job-listing/data-sci...

In [3]:
print("before",len(df))
df=df.drop_duplicates()
print("after",len(df))

before 718
after 718

In [4]:
df=df.loc[df["Salary Estimate"]!='-1']
len(df)

647

* Salary

In [5]:
df["Salary Estimate"].unique()

array(['$38.00 - $45.00 Per Hour (Employer est.)',
       '$120K - $130K (Employer est.)',
       '$66.82 - $80.54 Per Hour (Employer est.)',
       '$105K - $160K (Employer est.)', '$84K - $109K (Glassdoor est.)',
       '$101K - $172K (Employer est.)', '$117K - $229K (Employer est.)',
       '$63K - $105K (Glassdoor est.)',
       '$80.00 - $100.00 Per Hour (Employer est.)',
       '$130K - $150K (Employer est.)', '$110K - $125K (Employer est.)',
       '$66K - $70K (Employer est.)', '$110K - $200K (Employer est.)',
       '$63K - $117K (Glassdoor est.)', '$99K - $119K (Employer est.)',
       '$100K - $101K (Employer est.)', '$45K - $65K (Employer est.)',
       '$89K - $97K (Employer est.)', '$75K - $110K (Employer est.)',
       '$96K - $156K (Glassdoor est.)', '$82K - $175K (Employer est.)',
       '$97K - $145K (Employer est.)', '$131K - $181K (Glassdoor est.)',
       '$70K - $120K (Employer est.)', '$115K - $120K (Employer est.)',
       '$154K - $220K (Employer est.)', '$180K - $240K (Employer est.)',
       '$98K - $209K (Employer est.)', '$4K (Employer est.)',
       '$87K - $119K (Employer est.)', '$145K - $193K (Glassdoor est.)',
       '$130K - $145K (Employer est.)', '$162K - $297K (Employer est.)',
       '$138K - $209K (Employer est.)', '$70K - $116K (Glassdoor est.)',
       '$140K - $161K (Employer est.)', '$122K - $150K (Employer est.)',
       '$108K - $154K (Employer est.)', '$148K - $304K (Employer est.)',
       '$83K - $138K (Employer est.)', '$72K - $96K (Glassdoor est.)',
       '$90K - $115K (Employer est.)', '$120K - $150K (Employer est.)',
       '$5K - $7K (Employer est.)', '$172K - $258K (Employer est.)',
       '$63K - $98K (Employer est.)', '$137K - $255K (Employer est.)',
       '$96K - $144K (Employer est.)', '$40K - $72K (Glassdoor est.)',
       '$110K - $157K (Employer est.)', '$95K - $185K (Employer est.)',
       '$127K - $175K (Employer est.)', '$220K - $283K (Employer est.)',
       '$95K - $115K (Employer est.)', '$118K - $220K (Employer est.)',
       '$192K - $216K (Employer est.)', '$81K - $136K (Employer est.)',
       '$145K - $194K (Employer est.)', '$177K - $265K (Employer est.)',
       '$190K - $220K (Employer est.)', '$141K - $211K (Employer est.)',
       '$97K - $131K (Employer est.)', '$87K - $120K (Glassdoor est.)',
       '$102K - $138K (Employer est.)', '$152K - $328K (Employer est.)',
       '$133K - $209K (Employer est.)', '$119K - $206K (Employer est.)',
       '$76K - $126K (Glassdoor est.)', '$159K - $179K (Employer est.)',
       '$141K - $263K (Employer est.)', '$70K - $100K (Employer est.)',
       '$200K - $270K (Employer est.)', '$79K (Employer est.)',
       '$86K - $124K (Glassdoor est.)', '$120K - $149K (Glassdoor est.)',
       '$256K - $340K (Employer est.)', '$121K - $202K (Employer est.)',
       '$147K - $188K (Glassdoor est.)', '$90K - $165K (Employer est.)',
       '$160K - $269K (Employer est.)', '$113K - $158K (Employer est.)',
       '$112K - $154K (Employer est.)', '$126K - $213K (Employer est.)',
       '$108K - $185K (Employer est.)', '$178K - $233K (Glassdoor est.)',
       '$113K - $170K (Employer est.)', '$88K - $92K (Employer est.)',
       '$141K - $295K (Employer est.)', '$135K - $155K (Employer est.)',
       '$150K - $225K (Employer est.)', '$202K - $245K (Employer est.)',
       '$194K - $281K (Employer est.)', '$75K - $85K (Employer est.)',
       '$110K - $240K (Employer est.)', '$139K - $241K (Employer est.)',
       '$90K - $120K (Employer est.)', '$145K - $185K (Glassdoor est.)',
       '$160K - $175K (Employer est.)', '$158K - $208K (Employer est.)',
       '$138K - $294K (Employer est.)', '$120K - $287K (Employer est.)',
       '$165K - $300K (Employer est.)', '$124K - $190K (Employer est.)',
       '$119K - $156K (Employer est.)', '$135K - $197K (Glassdoor est.)',
       '$194K - $250K (Employer est.)', '$174K - $225K (Employer est.)',
       '$127K - $176K (Glassdoor est.)', '$89K - $122K (Employer est.)',
       '$133K - $192K (Glassdoor est.)', '$159K - $200K (Employer est.)',
       '$105K - $190K (Employer est.)', '$142K - $171K (Employer est.)',
       '$160K - $220K (Employer est.)', '$103K - $191K (Employer est.)',
       '$118K - $182K (Employer est.)', '$82K - $137K (Employer est.)',
       '$117K - $203K (Employer est.)', '$130K - $260K (Employer est.)',
       '$136K - $249K (Employer est.)', '$104K - $122K (Employer est.)',
       '$114K - $151K (Employer est.)', '$192K - $346K (Employer est.)',
       '$314K - $361K (Employer est.)', '$98K - $156K (Glassdoor est.)',
       '$115K - $173K (Glassdoor est.)', '$100K - $288K (Employer est.)',
       '$142K - $272K (Employer est.)', '$74K - $118K (Employer est.)',
       '$150K - $210K (Employer est.)', '$143K - $248K (Employer est.)',
       '$180K - $225K (Employer est.)', '$101K - $135K (Employer est.)',
       '$136K - $206K (Employer est.)', '$170K - $200K (Employer est.)',
       '$150K - $200K (Employer est.)', '$184K - $276K (Employer est.)',
       '$88K - $141K (Employer est.)', '$74K - $170K (Employer est.)',
       '$125K - $260K (Employer est.)', '$188K - $232K (Employer est.)',
       '$147K - $270K (Employer est.)', '$143K - $252K (Employer est.)',
       '$181K - $200K (Employer est.)', '$166K - $249K (Employer est.)',
       '$114K - $150K (Employer est.)', '$175K - $300K (Employer est.)',
       '$195K - $243K (Employer est.)', '$253K - $314K (Employer est.)',
       '$129K - $228K (Employer est.)', '$175K - $215K (Employer est.)',
       '$175K - $234K (Glassdoor est.)', '$110K - $175K (Employer est.)',
       '$187K - $203K (Employer est.)', '$75K - $163K (Employer est.)',
       '$110K - $224K (Employer est.)', '$144K - $240K (Employer est.)',
       '$122K - $140K (Employer est.)', '$200K - $260K (Employer est.)',
       '$145K - $180K (Employer est.)', '$138K - $190K (Employer est.)',
       '$157K - $218K (Employer est.)', '$126K - $189K (Employer est.)',
       '$20K - $240K (Employer est.)', '$100K - $150K (Employer est.)',
       '$85K - $127K (Glassdoor est.)', '$118K - $313K (Employer est.)',
       '$172K - $259K (Employer est.)', '$159K - $201K (Employer est.)',
       '$120K - $140K (Employer est.)', '$83K - $183K (Employer est.)',
       '$120K - $204K (Employer est.)', '$135K - $251K (Employer est.)',
       '$159K - $278K (Employer est.)', '$120K - $290K (Employer est.)',
       '$143K - $264K (Employer est.)', '$225K - $265K (Employer est.)',
       '$105K - $148K (Glassdoor est.)', '$115K - $260K (Employer est.)',
       '$133K - $236K (Employer est.)', '$52K - $200K (Employer est.)',
       '$160K - $235K (Employer est.)', '$140K - $280K (Employer est.)',
       '$21K - $312K (Employer est.)', '$182K - $232K (Employer est.)',
       '$86K - $120K (Employer est.)', '$161K - $202K (Employer est.)',
       '$165K - $242K (Employer est.)', '$133K - $190K (Employer est.)',
       '$175K - $242K (Employer est.)', '$146K - $270K (Employer est.)',
       '$158K - $176K (Employer est.)', '$57K - $110K (Employer est.)',
       '$115K - $213K (Employer est.)', '$163K - $285K (Employer est.)',
       '$152K - $253K (Employer est.)', '$183K - $274K (Employer est.)',
       '$116K - $166K (Employer est.)', '$147K - $260K (Employer est.)',
       '$100K - $110K (Employer est.)', '$98K - $165K (Employer est.)',
       '$143K - $215K (Employer est.)', '$158K - $243K (Employer est.)',
       '$202K - $277K (Employer est.)', '$194K - $258K (Employer est.)',
       '$172K - $246K (Employer est.)', '$95K - $211K (Employer est.)',
       '$202K - $237K (Employer est.)', '$145K - $240K (Employer est.)',
       '$104K - $127K (Employer est.)', '$225K - $240K (Employer est.)',
       '$127K - $214K (Glassdoor est.)', '$131K - $207K (Employer est.)',
       '$100K - $138K (Employer est.)', '$150K - $260K (Employer est.)',
       '$230K - $260K (Employer est.)', '$119K - $205K (Employer est.)',
       '$95K - $150K (Employer est.)', '$136K - $222K (Employer est.)',
       '$262K (Employer est.)', '$91K - $150K (Employer est.)',
       '$31K - $368K (Employer est.)', '$140K - $170K (Employer est.)',
       '$67K - $110K (Glassdoor est.)', '$180K - $230K (Glassdoor est.)',
       '$129K - $224K (Employer est.)', '$130K - $284K (Employer est.)',
       '$160K - $180K (Employer est.)', '$149K - $239K (Employer est.)',
       '$138K - $267K (Employer est.)', '$129K - $213K (Employer est.)',
       '$55K - $88K (Glassdoor est.)', '$200K - $285K (Employer est.)',
       '$31K - $51K (Employer est.)', '$69K - $99K (Glassdoor est.)',
       '$87K - $167K (Employer est.)', '$212K - $318K (Employer est.)',
       '$50K - $107K (Employer est.)', '$124K - $182K (Glassdoor est.)',
       '$206K - $281K (Employer est.)', '$159K - $178K (Employer est.)',
       '$178K - $253K (Employer est.)', '$148K - $290K (Employer est.)',
       '$78K - $128K (Glassdoor est.)', '$141K - $280K (Employer est.)',
       '$190K - $235K (Employer est.)', '$116K - $360K (Employer est.)',
       '$166K - $294K (Employer est.)', '$149K - $235K (Employer est.)',
       '$116K - $177K (Employer est.)', '$176K - $264K (Employer est.)',
       '$108K - $192K (Employer est.)', '$176K - $312K (Employer est.)',
       '$192K - $288K (Employer est.)', '$156K - $335K (Employer est.)',
       '$177K - $251K (Employer est.)', '$127K - $177K (Employer est.)',
       '$153K - $218K (Glassdoor est.)', '$120K - $154K (Glassdoor est.)',
       '$146K - $219K (Employer est.)', '$205K - $422K (Employer est.)',
       '$166K - $212K (Glassdoor est.)', '$167K - $284K (Employer est.)',
       '$141K - $282K (Employer est.)', '$111K - $200K (Employer est.)',
       '$155K - $220K (Glassdoor est.)', '$108K - $330K (Employer est.)',
       '$148K - $245K (Glassdoor est.)', '$142K - $309K (Employer est.)',
       '$131K - $190K (Glassdoor est.)', '$167K - $220K (Glassdoor est.)',
       '$189K - $284K (Employer est.)', '$92K - $137K (Glassdoor est.)',
       '$77K - $109K (Glassdoor est.)', '$156K - $209K (Employer est.)',
       '$184K - $281K (Employer est.)', '$68K - $234K (Employer est.)',
       '$89K - $112K (Glassdoor est.)', '$188K (Employer est.)',
       '$150K - $175K (Employer est.)', '$95K - $139K (Glassdoor est.)',
       '$142K - $264K (Employer est.)', '$107K - $147K (Glassdoor est.)',
       '$260K - $320K (Employer est.)', '$142K - $189K (Employer est.)',
       '$115K - $245K (Employer est.)', '$140K - $278K (Employer est.)',
       '$123K - $218K (Employer est.)', '$195K - $264K (Employer est.)',
       '$90K - $150K (Employer est.)',
       '$140.00 - $185.19 Per Hour (Employer est.)',
       '$133K - $275K (Employer est.)', '$139K - $197K (Glassdoor est.)',
       '$252K - $396K (Employer est.)', '$191K - $319K (Employer est.)',
       '$240K - $350K (Employer est.)', '$144K - $231K (Employer est.)',
       '$124K - $181K (Glassdoor est.)', '$115K - $187K (Glassdoor est.)',
       '$170K - $227K (Employer est.)', '$161K - $221K (Employer est.)',
       '$146K - $272K (Employer est.)', '$118K - $198K (Employer est.)',
       '$170K - $195K (Employer est.)', '$130K - $205K (Employer est.)',
       '$175K (Employer est.)', '$109K - $145K (Employer est.)',
       '$72K - $93K (Employer est.)', '$130K - $240K (Employer est.)',
       '$120K - $210K (Employer est.)', '$190K - $250K (Employer est.)',
       '$163K - $300K (Employer est.)', '$185K - $206K (Employer est.)',
       '$173K - $243K (Employer est.)', '$143K - $191K (Employer est.)',
       '$185K - $255K (Employer est.)', '$190K - $238K (Glassdoor est.)',
       '$95K - $182K (Employer est.)', '$186K - $279K (Employer est.)',
       '$134K - $200K (Employer est.)', '$102K - $235K (Employer est.)',
       '$141K - $189K (Glassdoor est.)', '$116K - $204K (Employer est.)',
       '$95K - $135K (Glassdoor est.)', '$165K - $185K (Employer est.)',
       '$178K (Employer est.)', '$107K - $179K (Employer est.)',
       '$83K - $130K (Glassdoor est.)', '$123K - $210K (Employer est.)',
       '$100K - $250K (Employer est.)', '$119K - $202K (Employer est.)',
       '$74K - $142K (Employer est.)', '$174K - $224K (Glassdoor est.)',
       '$174K - $194K (Employer est.)', '$75K - $100K (Employer est.)',
       '$230K - $280K (Employer est.)', '$170K (Employer est.)',
       '$72K - $128K (Glassdoor est.)', '$20K - $471K (Employer est.)',
       '$150K - $207K (Employer est.)', '$167K - $343K (Employer est.)',
       '$151K - $251K (Employer est.)', '$180K - $280K (Employer est.)',
       '$223K - $323K (Employer est.)', '$141K - $247K (Employer est.)',
       '$62K - $94K (Employer est.)', '$105K - $173K (Employer est.)',
       '$122K - $176K (Employer est.)', '$129K - $299K (Employer est.)',
       '$119K - $177K (Employer est.)', '$117K - $173K (Employer est.)',
       '$88K - $142K (Glassdoor est.)', '$180K - $210K (Employer est.)',
       '$81K - $123K (Glassdoor est.)', '$153K - $215K (Employer est.)',
       '$190K - $240K (Employer est.)', '$124K - $178K (Employer est.)',
       '$194K - $355K (Employer est.)', '$82K - $123K (Glassdoor est.)',
       '$140K - $268K (Employer est.)', '$132K - $217K (Employer est.)',
       '$144K - $209K (Employer est.)', '$148K - $276K (Employer est.)',
       '$167K - $296K (Employer est.)', '$67K - $97K (Employer est.)',
       '$186K - $276K (Employer est.)', '$143K - $181K (Employer est.)',
       '$115K - $156K (Employer est.)', '$143K - $208K (Employer est.)',
       '$157K - $217K (Employer est.)', '$113K - $150K (Employer est.)',
       '$121K - $221K (Employer est.)', '$157K - $267K (Employer est.)',
       '$110K (Employer est.)', '$104K - $348K (Employer est.)',
       '$133K - $322K (Employer est.)', '$323K - $485K (Employer est.)',
       '$10K - $12K (Employer est.)', '$142K - $188K (Glassdoor est.)',
       '$11K - $183K (Employer est.)', '$87K - $131K (Employer est.)',
       '$120K - $180K (Employer est.)', '$99K - $146K (Glassdoor est.)',
       '$137K - $211K (Employer est.)', '$137K - $196K (Employer est.)',
       '$139K - $209K (Employer est.)', '$141K - $187K (Employer est.)',
       '$157K - $279K (Employer est.)', '$137K - $280K (Employer est.)',
       '$156K - $214K (Glassdoor est.)', '$20K - $34K (Employer est.)',
       '$240K - $360K (Employer est.)', '$94K - $158K (Employer est.)',
       '$171K - $336K (Employer est.)', '$113K - $167K (Glassdoor est.)',
       '$100K - $105K (Employer est.)', '$127K - $274K (Employer est.)',
       '$99K - $146K (Employer est.)', '$149K - $208K (Glassdoor est.)',
       '$160K - $288K (Employer est.)', '$188K - $358K (Employer est.)',
       '$97K - $206K (Employer est.)', '$116K - $163K (Glassdoor est.)',
       '$96K - $131K (Glassdoor est.)', '$143K - $211K (Employer est.)',
       '$204K - $326K (Employer est.)', '$178K - $230K (Employer est.)',
       '$95K - $141K (Glassdoor est.)', '$82K - $118K (Glassdoor est.)',
       '$147K - $216K (Glassdoor est.)', '$116K - $220K (Employer est.)',
       '$109K - $163K (Employer est.)', '$90K - $116K (Glassdoor est.)',
       '$104K - $360K (Employer est.)', '$170K - $235K (Employer est.)',
       '$116K - $155K (Glassdoor est.)', '$133K - $197K (Employer est.)',
       '$220K - $260K (Employer est.)', '$145K - $250K (Employer est.)',
       '$117K - $153K (Glassdoor est.)', '$137K - $169K (Employer est.)',
       '$130K - $170K (Employer est.)', '$239K - $300K (Employer est.)',
       '$158K (Employer est.)', '$160K - $190K (Employer est.)',
       '$91K - $150K (Glassdoor est.)', '$120K (Employer est.)',
       '$77K - $182K (Employer est.)', '$85K - $106K (Glassdoor est.)',
       '$84K - $306K (Employer est.)', '$104K - $274K (Employer est.)',
       '$175K - $231K (Glassdoor est.)', '$119K - $187K (Glassdoor est.)',
       '$129K - $179K (Glassdoor est.)', '$106K - $110K (Employer est.)',
       '$70K - $138K (Employer est.)', '$181K - $313K (Employer est.)',
       '$128K - $183K (Glassdoor est.)', '$151K - $267K (Employer est.)',
       '$285K - $321K (Employer est.)', '$76K - $120K (Glassdoor est.)',
       '$97K - $138K (Glassdoor est.)', '$101K - $143K (Glassdoor est.)',
       '$105K - $207K (Employer est.)', '$120K - $170K (Glassdoor est.)',
       '$86K - $116K (Glassdoor est.)', '$88K - $157K (Employer est.)',
       '$142K - $178K (Employer est.)', '$172K - $210K (Employer est.)',
       '$82K - $143K (Glassdoor est.)', '$80K - $85K (Employer est.)',
       '$101K - $221K (Employer est.)', '$79K - $189K (Employer est.)',
       '$110K - $141K (Glassdoor est.)', '$156K - $200K (Glassdoor est.)',
       '$123K - $185K (Employer est.)', '$144K - $288K (Employer est.)',
       '$170K - $215K (Employer est.)', '$133K - $220K (Employer est.)',
       '$125K - $220K (Employer est.)', '$167K - $324K (Employer est.)',
       '$107K - $260K (Employer est.)', '$174K - $222K (Glassdoor est.)',
       '$87K - $175K (Employer est.)', '$98K - $144K (Glassdoor est.)',
       '$124K - $203K (Employer est.)', '$180K - $339K (Employer est.)',
       '$110K - $166K (Glassdoor est.)', '$136K - $229K (Employer est.)',
       '$155K - $258K (Employer est.)', '$115K - $160K (Glassdoor est.)',
       '$157K - $205K (Employer est.)', '$117K - $160K (Glassdoor est.)',
       '$59K - $105K (Glassdoor est.)', '$134K - $289K (Employer est.)',
       '$119K - $169K (Employer est.)', '$122K - $235K (Employer est.)',
       '$218K - $242K (Employer est.)', '$84K - $129K (Employer est.)',
       '$8K (Employer est.)', '$165K - $205K (Employer est.)',
       '$125K - $210K (Employer est.)', '$82K - $84K (Employer est.)',
       '$119K - $158K (Glassdoor est.)', '$160K - $240K (Employer est.)',
       '$130K - $180K (Employer est.)', '$123K - $150K (Employer est.)',
       '$117K - $211K (Employer est.)', '$139K - $181K (Employer est.)',
       '$122K - $238K (Employer est.)', '$112K - $199K (Employer est.)',
       '$126K - $210K (Employer est.)', '$99K - $157K (Glassdoor est.)',
       '$185K - $404K (Employer est.)', '$53K - $87K (Glassdoor est.)',
       '$104K - $269K (Employer est.)', '$130K - $189K (Employer est.)',
       '$160K - $200K (Employer est.)', '$100K - $130K (Employer est.)',
       '$108K - $150K (Glassdoor est.)', '$112K - $160K (Glassdoor est.)',
       '$76K - $172K (Employer est.)', '$82K - $100K (Employer est.)',
       '$112K - $164K (Glassdoor est.)', '$200K - $290K (Employer est.)',
       '$77K - $106K (Glassdoor est.)', '$192K - $242K (Glassdoor est.)',
       '$110K - $130K (Employer est.)', '$151K - $284K (Employer est.)',
       '$162K - $249K (Employer est.)', '$110K - $149K (Glassdoor est.)',
       '$235K - $265K (Employer est.)', '$104K - $167K (Employer est.)',
       '$80K - $100K (Employer est.)', '$104K - $170K (Glassdoor est.)',
       '$170K - $211K (Employer est.)', '$148K - $210K (Employer est.)',
       '$75K - $112K (Employer est.)', '$191K - $230K (Employer est.)',
       '$78K - $127K (Employer est.)', '$100K - $140K (Employer est.)',
       '$105K - $144K (Employer est.)', '$91K - $185K (Employer est.)',
       '$143K - $170K (Employer est.)', '$135K - $216K (Employer est.)',
       '$175K - $200K (Employer est.)', '$91K - $128K (Glassdoor est.)',
       '$155K - $162K (Employer est.)', '$175K - $220K (Employer est.)',
       '$90K - $135K (Employer est.)', '$157K - $216K (Employer est.)',
       '$150K - $190K (Employer est.)', '$108K - $156K (Glassdoor est.)',
       '$159K - $236K (Employer est.)', '$93K - $128K (Glassdoor est.)',
       '$73K - $106K (Glassdoor est.)', '$158K - $215K (Glassdoor est.)',
       '$32.32 - $51.46 Per Hour (Employer est.)',
       '$73K - $129K (Glassdoor est.)', '$148K - $237K (Employer est.)',
       '$48.19 - $75.93 Per Hour (Employer est.)', '$84K (Employer est.)'],
      dtype=object)

In [6]:
df["Employer est."]=df["Salary Estimate"].apply(lambda x: 1 if x.find('Employer est.')!=-1 else 0)

In [7]:
df["Per hour"]=df["Salary Estimate"].apply(lambda x: 1 if x.find('Per Hour')!=-1 else 0)

In [8]:
EstRemoved=df["Salary Estimate"].apply(lambda x: x.split(' (')[0])

In [9]:
removed_dk=EstRemoved.apply(lambda x: x.replace('$','').replace('K',''))
df["Min Salary"]=removed_dk.apply(lambda x: float(x.split(' - ')[0]))
removed_dk

0      38.00 - 45.00 Per Hour
1                   120 - 130
2      66.82 - 80.54 Per Hour
3                   105 - 160
4                    84 - 109
                ...
713                 148 - 237
714                 194 - 355
715                   63 - 98
716    48.19 - 75.93 Per Hour
717                        84
Name: Salary Estimate, Length: 647, dtype: object

In [10]:
removed_perhour=removed_dk.apply(lambda x: x.replace(' Per Hour',''))
removed_perhour

0      38.00 - 45.00
1          120 - 130
2      66.82 - 80.54
3          105 - 160
4           84 - 109
           ...
713        148 - 237
714        194 - 355
715          63 - 98
716    48.19 - 75.93
717               84
Name: Salary Estimate, Length: 647, dtype: object

In [11]:
df["Max Salary"]=removed_perhour.apply(lambda x: float(x.split(' - ')[1]) if x.find(' - ')!=-1 else float(x))

In [12]:
df["Avg Salary"]=(df["Min Salary"]+df["Max Salary"])/2

In [13]:
df.head(10)

,Job Title,Salary Estimate,Job Description,Rating,Company Name,Location,Size,Founded,Type of ownership,Industry,Sector,Revenue,URL,Employer est.,Per hour,Min Salary,Max Salary,Avg Salary
0,Data Analytics,$38.00 - $45.00 Per Hour (Employer est.),Minimum three years experience in data science...,3.9,J & S Consulting,"Tucker, GA",51 to 200 Employees,--,Company - Private,Information Technology Support Services,Information Technology,$5 to $25 million (USD),https://www.glassdoor.com/job-listing/data-ana...,1,1,38.00,45.00,41.50
1,Data Scientist,$120K - $130K (Employer est.),Data science: 1 year (Preferred). Expertise in...,4.0,element technologies,Remote,51 to 200 Employees,2000,Company - Private,Information Technology Support Services,Information Technology,Unknown / Non-Applicable,https://www.glassdoor.com/job-listing/data-sci...,1,0,120.00,130.00,125.00
2,Data Scientist,$66.82 - $80.54 Per Hour (Employer est.),End-to-end data and model pipeline deployment ...,4.4,Boston Technology,"Malvern, PA",51 to 200 Employees,2004,Company - Private,Information Technology Support Services,Information Technology,$5 to $25 million (USD),https://www.glassdoor.com/job-listing/data-sci...,1,1,66.82,80.54,73.68
3,Data Engineer,$105K - $160K (Employer est.),Communicates technical concepts to non-technic...,3.9,Costco Wholesale,"Dallas, TX",10000+ Employees,1976,Company - Public,General Merchandise & Superstores,Retail & Wholesale,Unknown / Non-Applicable,https://www.glassdoor.com/job-listing/data-eng...,1,0,105.00,160.00,132.50
4,Data Science Co-Op,$84K - $109K (Glassdoor est.),Work with source control tools like GIT to sav...,4.1,Hunter Engineering Company,"Bridgeton, MO",1001 to 5000 Employees,1946,Company - Private,Machinery Manufacturing,Manufacturing,$500 million to $1 billion (USD),https://www.glassdoor.com/job-listing/data-sci...,0,0,84.00,109.00,96.50
5,DATA SCIENCE: SAP Next Talent - Rotational Pro...,$101K - $172K (Employer est.),"Knowledge in Python, R, SQL and data science m...",4.2,SAP,"Palo Alto, CA",10000+ Employees,1972,Company - Public,Enterprise Software & Network Solutions,Information Technology,$10+ billion (USD),https://www.glassdoor.com/job-listing/data-sci...,1,0,101.00,172.00,136.50
7,Data Science,$117K - $229K (Employer est.),"Doctorate in Data Science, Mathematics, Statis...",4.2,Microsoft,"Redmond, WA",10000+ Employees,1975,Company - Public,Computer Hardware Development,Information Technology,$10+ billion (USD),https://www.glassdoor.com/job-listing/data-sci...,1,0,117.00,229.00,173.00
8,Data Engineer,$63K - $105K (Glassdoor est.),Experience with a wide range of data warehousi...,4.4,DotCMS,"Miami, FL",1 to 50 Employees,--,Company - Private,Research & Development,Management & Consulting,Unknown / Non-Applicable,https://www.glassdoor.com/job-listing/data-eng...,0,0,63.00,105.00,84.00
9,Data Scientist,$80.00 - $100.00 Per Hour (Employer est.),"A Bachelor's degree in Data Science, Statistic...",4.5,Signify Technology,Florida,51 to 200 Employees,2016,Company - Private,HR Consulting,Human Resources & Staffing,$5 to $25 million (USD),https://www.glassdoor.com/job-listing/data-sci...,1,1,80.00,100.00,90.00
11,Data Engineer,$130K - $150K (Employer est.),The Data Engineer role will be the technical l...,4.0,"Integrated Specialty Coverages, LLC",Remote,Unknown,--,Company - Private,Insurance Carriers,Insurance,Unknown / Non-Applicable,https://www.glassdoor.com/job-listing/data-eng...,1,0,130.00,150.00,140.00

* Location/State field

In [14]:
State=df["Location"].apply(lambda x: x.split(', ')[1] if x.find(', ')!=-1 else x)

Florida
Virgina
United States
Arizona
California
Vermot

In [15]:
FL_Fixed=State.apply(lambda x: "FL" if x.find('Florida')!=-1 else x)
Virginia_Fixed=FL_Fixed.apply(lambda x: "VA" if x.find("Virginia")!=-1 else x)
Texas_Fixed=Virginia_Fixed.apply(lambda x: "TX" if x.find("Texas")!=-1 else x)
Fulton=Texas_Fixed.apply(lambda x: "NY" if x.find("Fulton")!=-1 else x)
Carolina_Fixed=Fulton.apply(lambda x: "NC" if x.find("North Carolina")!=-1 else x)
California_Fixed=Carolina_Fixed.apply(lambda x: "CA" if x.find("California")!=-1 else x)
Dallas_Fixed=California_Fixed.apply(lambda x: "DFW" if x.find("Dallas-Fort Worth")!=-1 else x)
Arizona_Fixed=Dallas_Fixed.apply(lambda x: "AZ" if x.find("Arizona")!=-1 else x)
Vermont_Fixed=Arizona_Fixed.apply(lambda x: "VT" if x.find("Vermont")!=-1 else x)
Maryland_Fixed=Vermont_Fixed.apply(lambda x: "MD" if x.find("Maryland")!=-1 else x)
UnitedStates_Fixed=Maryland_Fixed.apply(lambda x: "US" if x.find("United States")!=-1 else x)
df["State"]=UnitedStates_Fixed

In [16]:
# For debuggin purposes
#df[df["Location"].str.contains("US")]

In [17]:
df["State"].unique()

array(['GA', 'Remote', 'PA', 'TX', 'MO', 'CA', 'WA', 'FL', 'VA', 'IL',
       'CO', 'MA', 'NY', 'VT', 'NJ', 'UT', 'RI', 'US', 'NC', 'OH', 'MD',
       'MN', 'TN', 'AZ', 'OR', 'DFW', 'WI', 'MI', 'CT', 'ID', 'IA', 'DC',
       'IN', 'KS', 'DE', 'LA'], dtype=object)

In [18]:
df.head()

,Job Title,Salary Estimate,Job Description,Rating,Company Name,Location,Size,Founded,Type of ownership,Industry,Sector,Revenue,URL,Employer est.,Per hour,Min Salary,Max Salary,Avg Salary,State
0,Data Analytics,$38.00 - $45.00 Per Hour (Employer est.),Minimum three years experience in data science...,3.9,J & S Consulting,"Tucker, GA",51 to 200 Employees,--,Company - Private,Information Technology Support Services,Information Technology,$5 to $25 million (USD),https://www.glassdoor.com/job-listing/data-ana...,1,1,38.00,45.00,41.50,GA
1,Data Scientist,$120K - $130K (Employer est.),Data science: 1 year (Preferred). Expertise in...,4.0,element technologies,Remote,51 to 200 Employees,2000,Company - Private,Information Technology Support Services,Information Technology,Unknown / Non-Applicable,https://www.glassdoor.com/job-listing/data-sci...,1,0,120.00,130.00,125.00,Remote
2,Data Scientist,$66.82 - $80.54 Per Hour (Employer est.),End-to-end data and model pipeline deployment ...,4.4,Boston Technology,"Malvern, PA",51 to 200 Employees,2004,Company - Private,Information Technology Support Services,Information Technology,$5 to $25 million (USD),https://www.glassdoor.com/job-listing/data-sci...,1,1,66.82,80.54,73.68,PA
3,Data Engineer,$105K - $160K (Employer est.),Communicates technical concepts to non-technic...,3.9,Costco Wholesale,"Dallas, TX",10000+ Employees,1976,Company - Public,General Merchandise & Superstores,Retail & Wholesale,Unknown / Non-Applicable,https://www.glassdoor.com/job-listing/data-eng...,1,0,105.00,160.00,132.50,TX
4,Data Science Co-Op,$84K - $109K (Glassdoor est.),Work with source control tools like GIT to sav...,4.1,Hunter Engineering Company,"Bridgeton, MO",1001 to 5000 Employees,1946,Company - Private,Machinery Manufacturing,Manufacturing,$500 million to $1 billion (USD),https://www.glassdoor.com/job-listing/data-sci...,0,0,84.00,109.00,96.50,MO

* Company Age

In [19]:
df["Founded"].unique()

array(['--', '2000', '2004', '1976', '1946', '1972', '1975', '2016',
       '2011', '1894', '2013', '1987', '-1', '2018', '1919', '1986',
       '1869', '2007', '2006', '1961', '2017', '1999', '1852', '1996',
       '1945', '2010', '1833', '2015', '1979', '1997', '2003', '1971',
       '1994', '2002', '2012', '1916', '1781', '2005', '1939', '1974',
       '2014', '2020', '1995', '1983', '1865', '1901', '1850', '1926',
       '1923', '1964', '1989', '1799', '1978', '2008', '1998', '1862',
       '2009', '1982', '1938', '1963', '1933', '1984', '1887', '1969',
       '1851', '1990', '1988', '1812', '1967', '1913', '2019', '1968',
       '2021', '2022', '1993', '1947', '1915', '1860', '1903', '2001',
       '1891', '1980', '1985', '1905', '1962', '1857', '1977', '1853',
       '1849', '1957', '1883', '1965', '1879', '1904', '1845', '1877',
       '1882', '1922', '1918', '1890', '1912', '1935', '1925', '1902',
       '1876', '1830', '1909', '1886', '1973', '1867', '1941', '1885',
       '1888', '1906', '2023', '1861', '1981', '1944', '1958', '1914',
       '1892', '1784', '1970', '1911', '1701', '1931', '1870'],
      dtype=object)

In [20]:
df["Companys Age"]=df["Founded"].apply(lambda x: int(2024-int(x)) if x!='--' and int(x)>0 else x)

* Description

In [21]:
df["MachineLearning"]=df["Job Description"].apply(lambda x: 1 if x.lower().find("machine learning")!=-1 else 0)
df["python"]=df["Job Description"].apply(lambda x: 1 if x.lower().find("python")!=-1 else 0)
df["power bi"]=df["Job Description"].apply(lambda x: 1 if x.lower().find("power bi")!=-1 else 0)
df["big data"]=df["Job Description"].apply(lambda x: 1 if x.lower().find("big data")!=-1 else 0)
df["sql"]=df["Job Description"].apply(lambda x: 1 if x.lower().find("sql")!=-1 else 0)

* Job Title

In [ ]:
#df["Job Title"][df["Job Title"].str.contains("")]
df["Job Title"].unique()

In [80]:
def JobTitleClean(title):
    if ("data scientist" in title.lower() or "science" in title.lower()) and (" ai " not in title.lower()):
        return "data scientist"
    elif ("data engineer" in title.lower() or "engineer" in title.lower()) and (" ai " not in title.lower()):
        return "data engineer"
    elif ("data analytics" in title.lower() or "analytics" in title.lower() or "analyst" in title.lower() or "insight" in title.lower()) and (" ai " not in title.lower()):
        return "data analyst"
    elif " ai " in title.lower() or "artifical intelligence" in title.lower() or "ai " in title.lower():
        return "artifical intelligence"
    elif "machine learning" in title.lower() or "/ ml" in title.lower():
        return "machine learning"
    elif "instructor" in title.lower() or "Lecturer" in title.lower() or "professor" in title.lower() or "class" in title.lower() or "supervisor" in title.lower() or "director" in title.lower():
        return "teaching"
    elif "statistician" in title.lower():
        return "statistician" 
    elif "deep" in title.lower():
        return "deep learning"
    elif "marketing" in title.lower():
        return "marketing related"
    elif "applied" in title.lower():
        return "applied scientist"
    elif "research" in title.lower():
        return "research"
    elif "business" in title.lower():
        return "business development"
    else:
        return "unknown"
df["Refined Title"]=df["Job Title"].apply(JobTitleClean)

In [82]:
df=df[df["Refined Title"]!="unknown"]

In [99]:
def seniority(title):
    if 'sr' in title.lower() or "expert" in title.lower() or 'senior' in title.lower() or 'sr' in title.lower() or 'principal' in title.lower() :
            return 'senior'
    elif 'president' in title.lower() or 'head' in title.lower() or"supervisor" in title.lower() or 'lead' in title.lower() or "associate" in title.lower() or "vp" in title.lower() :
        return 'head'
    elif 'manager' in title.lower():
        return 'manager'
    elif 'jr' in title.lower() or "junior" in title.lower():
        return 'jr'
    elif "staff" in title.lower():
        return "staff"
    else:
        return 'not applicable'
seniorityOfJobs=df["Job Title"].apply(seniority)

In [102]:
seniorityOfJobs.unique()
df["Seniority"]=seniorityOfJobs

C:\Users\testr\AppData\Local\Temp\ipykernel_10292\241210052.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Seniority"]=seniorityOfJobs

In [112]:
df.columns

Index(['Job Title', 'Salary Estimate', 'Job Description', 'Rating',
       'Company Name', 'Location', 'Size', 'Founded', 'Type of ownership',
       'Industry', 'Sector', 'Revenue', 'URL', 'Employer est.', 'Per hour',
       'Min Salary', 'Max Salary', 'Avg Salary', 'State', 'Companys Age',
       'MachineLearning', 'python', 'power bi', 'big data', 'sql',
       'Refined Title', 'Seniority'],
      dtype='object')

* hourly to annual salary

In [113]:
df["Min Salary"]=df.apply(lambda x: x["Min Salary"]*2 if x["Per hour"]==1 else x["Min Salary"],axis=1)
df["Max Salary"]=df.apply(lambda x: x["Max Salary"]*2 if x["Per hour"]==1 else x["Max Salary"],axis=1)

In [119]:
df[df["Per hour"]==1]

,Job Title,Salary Estimate,Job Description,Rating,Company Name,Location,Size,Founded,Type of ownership,Industry,...,Avg Salary,State,Companys Age,MachineLearning,python,power bi,big data,sql,Refined Title,Seniority
0,Data Analytics,$38.00 - $45.00 Per Hour (Employer est.),Minimum three years experience in data science...,3.9,J & S Consulting,"Tucker, GA",51 to 200 Employees,--,Company - Private,Information Technology Support Services,...,41.500,GA,--,0,0,0,0,1,data analyst,not applicable
2,Data Scientist,$66.82 - $80.54 Per Hour (Employer est.),End-to-end data and model pipeline deployment ...,4.4,Boston Technology,"Malvern, PA",51 to 200 Employees,2004,Company - Private,Information Technology Support Services,...,73.680,PA,20,1,1,0,0,0,data scientist,not applicable
9,Data Scientist,$80.00 - $100.00 Per Hour (Employer est.),"A Bachelor's degree in Data Science, Statistic...",4.5,Signify Technology,Florida,51 to 200 Employees,2016,Company - Private,HR Consulting,...,90.000,FL,8,0,0,0,0,1,data scientist,not applicable
387,"Vice President, Chief Data and Analytics Offic...",$140.00 - $185.19 Per Hour (Employer est.),Bachelor's degree in a work-related field/disc...,3.6,Stanford Health Care,"Palo Alto, CA",10000+ Employees,1957,Hospital,Health Care Services & Hospitals,...,162.595,CA,67,0,0,0,0,0,data analyst,head
711,Asset Management Data Scientist,$32.32 - $51.46 Per Hour (Employer est.),"Recommend system enhancements, modifications, ...",4.4,UDOT,"Salt Lake City, UT",1001 to 5000 Employees,1911,Government,State & Regional Agencies,...,41.890,UT,113,0,0,0,0,1,data scientist,not applicable
716,DISTRICT STATISTICIAN,$48.19 - $75.93 Per Hour (Employer est.),Requirements: Bachelor’s degree in a job-relat...,3.6,Park City School District,"Park City, UT",201 to 500 Employees,1946,School / School District,Preschools & Child Care Services,...,62.060,UT,78,0,0,0,0,0,statistician,not applicable

In [120]:
df.to_csv('Data Science Jobs preprocessed.csv')